config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  devise_for :users
  resources :books, only: [:new, :index, :show, :edit, :update, :create, :destroy]
  resources :users, only: [:index, :show, :edit, :update]


  get "/home/about" => "homes#about", as: "about"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :profile_image
  belongs_to :user

  validates :title, presence: true

  validates :body, {presence: true, length: {maximum:200}}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :books, dependent: :destroy

  validates :name, uniqueness: true, length: { minimum: 2, maximum: 20 }

  validates :introduction, length: {maximum:50}

  def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/default-image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
      user_path(resource)
  end

  def after_sign_out_path_for(resource)
      root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_user, only: [:edit]
  def new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save #成功したとき
      flash[:notice]  = 'You have created book successfully.'
      redirect_to book_path(@book)
    else #失敗したとき
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def update
   @book = Book.find(params[:id])

    if @book.update(book_params)
      flash[:notice]  = 'You have updated book successfully.'
      redirect_to book_path(@book.id)
    else
      # @book = Book.find(params[:id])
      @user = @book.user
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to "/books"
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to books_path unless @user == current_user
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def about
  end

  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit]
  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    @book = @user
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice]  = 'You have updated user successfully.'
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def correct_user
    @user = User.find(params[:id])
    @books = @user.books
    redirect_to(user_path(current_user.id)) unless @user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_books.html.erb
<div class="col-md-3">
  <h2>User info</h2>
  <%= image_tag user.get_profile_image(100,100) %>
  <table class="table">
    <tbody><tr></tr>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
    </tbody>
  </table>

  <div class="row">
    <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
    <% end %>
  </div>

  <h2 class="mt-3">New book</h2>
  <%= form_with model: book do |f| %>
  <div class="field">
    <label for="book_title">Title</label>
    <div><%= f.text_field :title %></div>
  </div>

  <div class="field">
    <label for="book_opinion">Opinion</label>
    <div><%= f.text_area :body %></div>
  </div>

  <div class="field">
    <%= f.submit 'Create Book', class: "btn btn-success" %>
  </div>
  <% end %>
</div>

app/views/books/edit.html.erb
<body>
    <main>
      <p id="notice"></p>
      <div class="container">
        <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
          <h1>Editing Book</h1>
          <div>
          <% if @book.errors.any? %>
          <%= @book.errors.count %>errors prohibited this obj from being saved:
          <ul>
            <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
          <% end %>
          </div>

          <%= form_with model: @book, url: book_path(@book.id), method: :patch  do |f| %>
          <div class="form-group">
            <div class="field">
              <label for="book_title">Title</label>
              <div><%= f.text_field :title, :size=>"60" %></div>
            </div>
          </div>

          <div class="form-group">
            <div class="field">
              <label for="book_opinion">Opinion</label>
              <div><%= f.text_area :body, :size=>"60" %></div>
            </div>
          </div>

          <div class="form-group">
            <%= f.submit "Update Book", class: "btn btn-success" %>
          </div>
          <% end %>

          <%= link_to "Show", book_path(@book.id) %>
          |
          <%= link_to "Back", books_path %>

        </div>
      </div>
    </main>
</body>

app/views/books/index.html.erb
<body>
    <main>

        <div class="container px-5 px-sm-0">
          <div>
          <% if @book.errors.any? %>
          <%= @book.errors.count %>errors prohibited this obj from being saved:
          <ul>
            <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
          <% end %>
          </div>
             <div class="row">
               <%= render 'books', book: @book, user: @user %>


                  <div class="col-md-8 offset-md-1">
                    <h2>Books</h2>
                    <table class="table table-hover table-inverse">
                      <thead>
                        <tr>
                          <th></th>
                          <th>Title</th>
                          <th>Opinion</th>
                          <th colspan="3"></th>
                        </tr>
                      </thead>
                      <tbody>
                        <% @books.each do |book| %>
                        <tr>
                          <th>
                            <%= link_to user_path(book.user.id) do %>
                              <%= image_tag book.user.get_profile_image(80,80) %>
                            <% end %>
                          </th>
                          <th>
                            <%= link_to book_path(book.id) do %>
                              <%= book.title %>
                            <% end %>
                          </th>
                          <th><%= book.body %></th>
                          <th colspan="3"></th>
                        </tr>
                        <% end %>
                      </tbody>
                    </table>
                  </div>
              </div>
        </div>
     </main>
</body>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<body>
    <main>
        <p><%= flash[:notice] %></p>
        <div class="container px-5 px-sm-0">
             <div class="row">
               <%= render 'books', book: @book_new, user: @user %>


                  <div class="col-md-8 offset-md-1">
                    <h2>Book detail</h2>
                    <table class="table table-hover table-inverse">
                      <tbody>
                        <tr>
                          <th>
                            <%= link_to user_path(@user.id) do %>
                              <%= image_tag @book.user.get_profile_image(100,100) %><br>
                              <%= @book.user.name %>
                            <% end %>
                          </th>
                          <th>
                            <%= link_to book_path(@book.id) do %>
                              <%= @book.title %>
                            <% end %>
                          </th>
                          <th><%= @book.body %></th>
                          <% if @book.user == current_user %>
                          <th>
                            <%= link_to "Edit", edit_book_path %>
                          </th>
                          <% end %>
                          <th>
                            <% if @book.user == current_user %>
                              <%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>
                            <% end %>
                          </th>
                          <th colspan="5"></th>
                        </tr>
                      </tbody>
                    </table>
                  </div>
              </div>
        </div>
     </main>
</body>

app/views/homes/about.html.erb
<html>
  <main>
    <p id="notice"></p>
    <div class="container">
      <div class="row">
        <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
      </div>
    </div>
  </main>
</html>

app/views/homes/top.html.erb
<html>
  <main>
    <p><%= flash[:notice] %></p>
    <p id="notice"></p>
    <div class="container">
      <div class="row">
        <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
          <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!!</h1>
          <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>,</p>
          <p>you can share and exchange  your opinions , inpressions , and emotions</p>
          <p> about various books!</p>

          <div class="btn-wrapper col-10 mx-auto">
            <div class="row">
              <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
            </div>

            <div class="row">
              <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <header class="shadow-sm bg-dark">
      <nav class="navbar navbar-expand-lg navbar-dark">
        <div class="container">
          <a class="navbar-brand text-white" href="/"><span>Bookers</span></a>
          <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon "></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %><!-- ログインしている -->
              <div class="text-white">
                <li class="nav-item link-danger">
                <i class="fas fa-home"></i><%= link_to "Home", user_path(current_user.id) , class: "text-light" %>
                </li>
              </div>
              <div class="text-white">
                <li class="nav-item">
                <i class="fas fa-users"></i><%= link_to "Users", "/users" , class: "text-light" %>
                </li>
              </div>
              <div class="text-white">
                <li class="nav-item">
                <i class="fas fa-book-open"></i><%= link_to "Books", "/books" , class: "text-light" %>
                </li>
              </div>
              <div class="text-white">
                <li class="nav-item">
                <i class="fas fa-sign-out-alt"></i><%= link_to "Log out", destroy_user_session_path, method: :delete , class: "text-light" %>
                </li>
              </div>


              <% else %><!-- ログインしていない -->
              <div class="text-white">
                <li class="nav-item link-danger">
                <i class="fas fa-home"></i><%= link_to "Home", root_path , class: "text-light" %>
                </li>
              </div>
              <div class="text-white">
                <li class="nav-item">
                <i class="fas fa-link"></i><%= link_to "About", about_path , class: "text-light" %>
                </li>
              </div>
              <div class="text-white">
                <li class="nav-item">
                <i class="fas fa-user-plus"></i><%= link_to "Sign up", new_user_registration_path , class: "text-light" %>
                </li>
              </div>
              <div class="text-white">
                <li class="nav-item">
                <i class="fas fa-sign-in-alt"></i><%= link_to "Log in", new_user_session_path , class: "text-light" %>
                </li>
              </div>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
  </header>
    <main class="mb-auto">
      <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<body>
    <main>
      <p id="notice"></p>
      <div class="container">
        <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
          <h1>User info</h1>
          <div>
          <% if @user.errors.any? %>
          <%= @user.errors.count %>errors prohibited this obj from being saved:
          <ul>
            <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
          <% end %>
          </div>

          <%= form_with model: @user, url: user_path(@user.id), method: :patch  do |f| %>
          <div class="form-group">
            <div class="field">
              <label for="inputName">Name</label>
              <div><%= f.text_area :name, :size=>"60" %></div>
            </div>
          </div>

          <div class="form-group">
            <div class="field">
              <label for="inputImage">Image</label>
              <div><%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*", :size=>"60" %></div>
            </div>
          </div>

          <div class="form-group">
            <div class="field">
              <label for="inputIntroduction">Introduction</label>
              <div><%= f.text_area :introduction, :size=>"60" %></div>
            </div>
          </div>

          <div class="form-group">
            <%= f.submit "Update User", class: "btn btn-secondary" %>
          </div>
          <% end %>
        </div>
      </div>
    </main>
</body>

app/views/users/index.html.erb
<body>
    <main>
        <div class="container px-5 px-sm-0">
          <div class="row">
            <%= render 'books/books', book: @book, user: @user %>
            <div class="col-md-8 offset-md-1">
                    <h2>Users</h2>
                    <table class="table table-hover table-inverse">
                      <thead>
                        <tr>
                          <th>image</th>
                          <th>name</th>
                          <th colspan="3"></th>
                        </tr>
                      </thead>
                      <tbody>
                        <% @books.each do |book| %>
                        <tr>
                          <th>
                              <%= image_tag book.user.get_profile_image(80,80) %>
                          </th>
                          <th>
                            <%= book.user.name %>
                          </th>
                          <th><%= link_to 'Show', user_path(book.user.id) %></th>
                          <th colspan="3"></th>
                        </tr>
                        <% end %>
                      </tbody>
                    </table>
                  </div>
          </div>
        </div>
    </main>
</body>

app/views/users/show.html.erb
<body>
    <main>
      <p><%= flash[:notice] %></p>
        <div class="container px-5 px-sm-0">
          <div class="row">
            <%= render 'books/books', book: @book, user: @user %>
            <div class="col-md-8 offset-md-1">
                    <h2>Books</h2>
                    <table class="table table-hover table-inverse">
                      <thead>
                        <tr>
                          <th></th>
                          <th>Title</th>
                          <th>Opinion</th>
                          <th colspan="3"></th>
                        </tr>
                      </thead>
                      <tbody>
                        <% @books.each do |book| %>
                        <tr>
                          <th>
                            <%= link_to user_path(book.user.id) do %>
                              <%= image_tag book.user.get_profile_image(80,80) %>
                            <% end %>
                          </th>
                          <th>
                            <%= link_to book.title, book_path(book.id)  %>
                          </th>
                          <th><%= book.body %></th>
                          <th colspan="3"></th>
                        </tr>
                        <% end %>
                      </tbody>
                    </table>
            </div>
          </div>
        </div>
    </main>
</body>